# Generated by Django 4.2.3 on 2023-08-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_myuploadfile_delete_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myuploadfile',
        ),
    ]
