# Generated by Django 4.2.3 on 2023-08-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_myuploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('accountid', models.IntegerField()),
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('projeid', models.IntegerField()),
                ('proje', models.CharField(max_length=225)),
                ('dosyaadi', models.CharField(max_length=125)),
                ('dosyatipi', models.CharField(max_length=20)),
                ('dosyayol', models.CharField(max_length=300)),
                ('yüklediğikonu', models.CharField(max_length=300)),
                ('yüklemetarih', models.DateField(auto_now=True)),
                ('yüklemesaat', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='myfilemodel',
            old_name='dosya',
            new_name='file',
        ),
    ]
