# Generated by Django 4.2.3 on 2023-08-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_accounts_rename_dosya_myfilemodel_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='yüklediğikonu',
            new_name='yukledigikonu',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='yüklemesaat',
            new_name='yuklemesaat',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='yüklemetarih',
            new_name='yuklemetarih',
        ),
    ]
