# Generated by Django 4.2.3 on 2023-11-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_veriler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veriler',
            name='sifre',
            field=models.CharField(max_length=60),
        ),
    ]
